#!/bin/bash

echo "[*] Uninstalling Roblox..."

rm -rf "$HOME/Library/Application Support/Roblox"
rm -rf "$HOME/Library/Logs/Roblox"
rm -rf "$HOME/Library/Caches/com.roblox.Roblox"
rm -rf "/Applications/Roblox.app"

echo "[*] Uninstalling MacSploit..."

rm -rf "$HOME/Library/Application Support/MacSploit"
rm -rf "/Applications/MacSploit.app"

echo "[✓] Uninstall complete."

echo "[*] Reinstalling MacSploit..."
curl -L https://raw.githubusercontent.com/alexkkork/reinstall/refs/heads/main/macsploit-install | bash
